version: '3.5'
services:
  temporal:
    image: temporalio/auto-setup:1.15.1
    ports:
      - '7233:7233'
    environment:
      - 'DB=postgresql'
      - 'DB_PORT=5432'
      - 'POSTGRES_USER=temporal'
      - 'POSTGRES_PWD=temporal'
      - 'POSTGRES_SEEDS=temporal-postgresql'
      - 'DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml'
    depends_on:
      - temporal-postgresql
      - temporal-elasticsearch
    healthcheck:
      { test: ['CMD', 'curl', '-f', 'http://localhost:7233/health'], interval: 10s, timeout: 2s, retries: 10 }

  temporal-web:
    image: temporalio/web:1.15.0
    environment:
      - 'TEMPORAL_GRPC_ENDPOINT=temporal:7233'
      - 'TEMPORAL_PERMIT_WRITE_API=true'
    ports:
      - '8088:8088'
    depends_on:
      - temporal

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=appUser
      - MONGO_INITDB_ROOT_PASSWORD=appPassword
      - MONGO_INITDB_DATABASE=temporal-api
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init-dev.js

  temporal-postgresql:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=temporal'
      - 'POSTGRES_PASSWORD=temporal'
      - 'POSTGRES_DB=temporal'
    healthcheck: { test: ['CMD', 'pg_isready', '-U', 'temporal'], interval: 10s, timeout: 2s, retries: 10 }

  temporal-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms4g -Xmx4g'
    ports:
      - '9200:9200'

  temporal-api:
    restart: always
    build:
      context: ./
      dockerfile: ./temporal-api.dockerfile
    env_file: ./.env
    ports:
      - '6000:6000'
    depends_on:
      - temporal
      - mongodb

  temporal-worker:
    restart: always
    build:
      context: ./
      dockerfile: ./temporal-worker.dockerfile
    env_file: ./.env
    depends_on:
      - temporal
      - mongodb